### ISSUE TITLE
Error in opencv, img_hash not found

### ISSUE THREAD

**Issue by ctgreybeard** [EhsanKia/CatalogScanner#1]
Just cloned to my Mac (Catalina) and got an error in OpenCV I believe ...

```
(.env) ╭─dad@ruusan.greybeard.org ~/work/Projects/CatalogScanner ‹master*›
╰─(.env) ➤  python scanner.py /Users/dad/Dropbox/Photos/Switch/2020/09/07/2020090708554401-02CB906EA538A35643C1E1484C4B947D.mp4
I0907 10:11:30.954331 4439834048 scanner.py:38] Detected scan mode: catalog
Traceback (most recent call last):
  File "scanner.py", line 102, in <module>
    app.run(main)
  File "/Users/dad/work/Projects/CatalogScanner/.env/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/dad/work/Projects/CatalogScanner/.env/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "scanner.py", line 89, in main
    result = scan_media(
  File "scanner.py", line 49, in scan_media
    return SCANNERS[mode].scan(filename, locale=locale, **kwargs)
  File "/Users/dad/work/Projects/CatalogScanner/catalog.py", line 57, in scan
    item_rows = parse_video(video_file, for_sale)
  File "/Users/dad/work/Projects/CatalogScanner/catalog.py", line 95, in parse_video
    all_rows = _dedupe_rows(all_rows)
  File "/Users/dad/work/Projects/CatalogScanner/catalog.py", line 218, in _dedupe_rows
    row_hash = str(cv2.img_hash.blockMeanHash(row, mode=1)[0])
AttributeError: module 'cv2.cv2' has no attribute 'img_hash'
```

`pip` ran without problems:

```
(.env) ╭─dad@ruusan.greybeard.org ~/work/Projects/CatalogScanner ‹master*›
╰─(.env) ➤  pip install -r requirements.txt
Collecting absl-py==0.9.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/1a/53/9243c600e047bd4c3df9e69cfabc1e8004a82cac2e0c484580a78a94ba2a/absl-py-0.9.0.tar.gz (104kB)
     |████████████████████████████████| 112kB 2.1MB/s
Collecting imagehash==4.1.0 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/1a/5d/cc81830be3c4705a46cdbca74439b67f1017881383ba0127c41c4cecb7b3/ImageHash-4.1.0.tar.gz (291kB)
     |████████████████████████████████| 296kB 9.3MB/s
Collecting opencv-contrib-python==4.2.0.34 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/d1/29/0e9583011e535c23b92a0ec64ff449b9e05d86423a6e5a16385f569b04d6/opencv_contrib_python-4.2.0.34-cp38-cp38-macosx_10_9_x86_64.whl (60.3MB)
     |████████████████████████████████| 60.3MB 9.3MB/s
Collecting opencv-python==4.2.0.34 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/f6/cd/0642144e580aa2fda0dc70276a432a48542351a620d26f0d1e3c5169ff49/opencv_python-4.2.0.34-cp38-cp38-macosx_10_9_x86_64.whl (49.1MB)
     |████████████████████████████████| 49.1MB 15.0MB/s
Collecting Pillow==7.1.2 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/20/20/a0f9f20469aae7017a578fdc4c55ea18f7c8911d2d10668687f95748442b/Pillow-7.1.2-cp38-cp38-macosx_10_10_x86_64.whl
Collecting pytesseract==0.3.4 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/1d/d8/521db389ff0aae32035bfda6ed39cb2c2e28521c47015f6431f07460c50a/pytesseract-0.3.4.tar.gz
Collecting six (from absl-py==0.9.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting numpy (from imagehash==4.1.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/2f/c0/09c526b4167ed4dd3bcb6d6aa2103b4b50899e8eae89acde6455d43a37e4/numpy-1.19.1-cp38-cp38-macosx_10_9_x86_64.whl (15.3MB)
     |████████████████████████████████| 15.3MB 10.7MB/s
Collecting scipy (from imagehash==4.1.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/8a/84/568ec7727bc789a9b623ec2652043ad3311d7939f152e81cb5d699bfb9b1/scipy-1.5.2-cp38-cp38-macosx_10_9_x86_64.whl (28.9MB)
     |████████████████████████████████| 29.0MB 11.5MB/s
Collecting PyWavelets (from imagehash==4.1.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/77/fa/cd182609e276d8ea7315a084cf2acbd0f39751e56562555bd8e4a0131498/PyWavelets-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (4.3MB)
     |████████████████████████████████| 4.4MB 16.0MB/s
Installing collected packages: six, absl-py, numpy, scipy, Pillow, PyWavelets, imagehash, opencv-contrib-python, opencv-python, pytesseract
  Running setup.py install for absl-py ... done
  Running setup.py install for imagehash ... done
  Running setup.py install for pytesseract ... done
Successfully installed Pillow-7.1.2 PyWavelets-1.1.1 absl-py-0.9.0 imagehash-4.1.0 numpy-1.19.1 opencv-contrib-python-4.2.0.34 opencv-python-4.2.0.34 pytesseract-0.3.4 scipy-1.5.2 six-1.15.0
WARNING: You are using pip version 19.2.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Python is:
```
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18)
[Clang 6.0 (clang-600.0.57)]
```

**Comment by ctgreybeard** [comment]
Any thoughts on this?  I also installed under ubuntu and get the same error with python 3.8.

**Comment by ctgreybeard** [comment]
I found the issue!

I uninstalled both `opencv-python` and `opencv-contrib-python` and then installed **only** `opencv-contrib-python`.

According to the `opencv-contrib-python` [installation docs](https://pypi.org/project/opencv-contrib-python/) "There are four different packages and you should select only one of them. Do not install multiple different packages in the same environment. "

In your requirements you have both opencv-python and opencv-contrib-python. Because of the installation order the `opencv-python` gets precedence and the other is masked. 

I suggest you remove `opencv-python` from requirements.txt.

**Comment by EhsanKia** [comment]
Err, I somehow had my own repo set to "Unwatched" and completely missed this. Sorry about that and I'm glad you found the solution. And that you @rohm1 for the fix :)
